# **Task 1: Data Preparation (with scikit-learn)**

In [19]:
import sys, os
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "../..")))

from src.preprocessing.regex_tokenizer import RegexTokenizer
from representations.count_vectorizer import CountVectorizer


texts = [
    "This movie is fantastic and I love it!",
    "I hate this film, it's terrible.",
    "The acting was superb, a truly great experience.",
    "What a waste of time, absolutely boring.",
    "Highly recommend this, a masterpiece.",
    "Could not finish watching, so bad."
]
labels = [1, 0, 1, 0, 1, 0]

tokenizer = RegexTokenizer()
vectorizer = CountVectorizer(tokenizer)

X = vectorizer.fit_transform(texts)
print("Vocabulary size:", len(vectorizer.vocabulary_))

Vocabulary size: 39

In [1]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import pandas as pd

In [2]:
texts = [
    "This movie is fantastic and I love it!",
    "I hate this film, it's terrible.",
    "The acting was superb, a truly great experience.",
    "What a waste of time, absolutely boring.",
    "Highly recommend this, a masterpiece.",
    "Could not finish watching, so bad."
]

labels = [1, 0, 1, 0, 1, 0]  # 1 = positive, 0 = negative

In [3]:
# CountVectorizer
vectorizer1 = CountVectorizer(stop_words='english')

X = vectorizer1.fit_transform(texts)

df = pd.DataFrame(X.toarray(), columns=vectorizer1.get_feature_names_out())
df['label'] = labels

df.head()

,absolutely,acting,bad,boring,experience,fantastic,film,finish,great,hate,...,masterpiece,movie,recommend,superb,terrible,time,truly,waste,watching,label
0,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0
2,0,1,0,0,1,0,0,0,1,0,...,0,0,0,1,0,0,1,0,0,1
3,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,1

In [4]:
# TF-IDF
vectorizer2 = TfidfVectorizer(stop_words='english')

X = vectorizer2.fit_transform(texts)

df = pd.DataFrame(X.toarray(), columns=vectorizer2.get_feature_names_out())
df['label'] = labels

df.head()

,absolutely,acting,bad,boring,experience,fantastic,film,finish,great,hate,...,masterpiece,movie,recommend,superb,terrible,time,truly,waste,watching,label
0,0.0,0.000000,0.0,0.0,0.000000,0.57735,0.00000,0.0,0.000000,0.00000,...,0.00000,0.57735,0.00000,0.000000,0.00000,0.0,0.000000,0.0,0.0,1
1,0.0,0.000000,0.0,0.0,0.000000,0.00000,0.57735,0.0,0.000000,0.57735,...,0.00000,0.00000,0.00000,0.000000,0.57735,0.0,0.000000,0.0,0.0,0
2,0.0,0.447214,0.0,0.0,0.447214,0.00000,0.00000,0.0,0.447214,0.00000,...,0.00000,0.00000,0.00000,0.447214,0.00000,0.0,0.447214,0.0,0.0,1
3,0.5,0.000000,0.0,0.5,0.000000,0.00000,0.00000,0.0,0.000000,0.00000,...,0.00000,0.00000,0.00000,0.000000,0.00000,0.5,0.000000,0.5,0.0,0
4,0.0,0.000000,0.0,0.0,0.000000,0.00000,0.00000,0.0,0.000000,0.00000,...,0.57735,0.00000,0.57735,0.000000,0.00000,0.0,0.000000,0.0,0.0,1